# Generated by Django 5.0.3 on 2024-03-17 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question_DB',
            new_name='Question',
        ),
        migrations.RemoveField(
            model_name='exam_model',
            name='question_paper',
        ),
        migrations.RemoveField(
            model_name='test',
            name='question_paper',
        ),
        migrations.AddField(
            model_name='exam_model',
            name='questions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='instructor.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='instructor.question'),
            preserve_default=False,
        ),
    ]
