# Generated by Django 5.0.3 on 2024-03-22 07:34

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_rename_question_db_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='status',
            new_name='noteStatus',
        ),
        migrations.AddField(
            model_name='page',
            name='completionQuestion',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='completionQuestionAns',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module',
            name='overview',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
