# Generated by Django 5.0.3 on 2024-03-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_rename_status_page_notestatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='answerHint',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
