# Generated by Django 5.0.3 on 2024-03-23 21:25

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0006_rename_percent_courseprogress_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_paper',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='test',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='exam_model',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='question_paper',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='exam_model',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='exam_model',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='exam_model',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='exam_model',
            name='total_marks',
        ),
        migrations.RemoveField(
            model_name='test',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='test',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='test',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='test',
            name='total_marks',
        ),
        migrations.CreateModel(
            name='ModelQuestion',
            fields=[
                ('qno', models.AutoField(primary_key=True, serialize=False)),
                ('question', ckeditor_uploader.fields.RichTextUploadingField()),
                ('optionA', models.CharField(max_length=255)),
                ('optionB', models.CharField(max_length=255)),
                ('optionC', models.CharField(max_length=255)),
                ('optionD', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('ans_description', models.TextField()),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modeExam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='instructor.exam_model')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('qno', models.AutoField(primary_key=True, serialize=False)),
                ('question', ckeditor_uploader.fields.RichTextUploadingField()),
                ('optionA', models.CharField(max_length=255)),
                ('optionB', models.CharField(max_length=255)),
                ('optionC', models.CharField(max_length=255)),
                ('optionD', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('ans_description', models.TextField()),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('testExam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='instructor.test')),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Question_Paper',
        ),
    ]
