# Generated by Django 5.0.3 on 2024-03-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0009_test_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelquestion',
            name='optionA_slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelquestion',
            name='optionB_slug',
            field=models.SlugField(default='bu', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelquestion',
            name='optionC_slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelquestion',
            name='optionD_slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testquestion',
            name='optionA_slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testquestion',
            name='optionB_slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testquestion',
            name='optionC_slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testquestion',
            name='optionD_slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
