# Generated by Django 5.0.3 on 2024-03-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0010_modelquestion_optiona_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelquestion',
            name='optionA_slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='modelquestion',
            name='optionB_slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='modelquestion',
            name='optionC_slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='modelquestion',
            name='optionD_slug',
            field=models.SlugField(),
        ),
    ]
