# Generated by Django 5.0.3 on 2024-03-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0011_alter_modelquestion_optiona_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='total_mark',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
