# Generated by Django 5.0.3 on 2024-03-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0013_examstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='examstatus',
            name='response_status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
