# Generated by Django 5.0.3 on 2024-03-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0014_examstatus_response_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examstatus',
            name='response_status',
            field=models.CharField(max_length=255),
        ),
    ]
