# Generated by Django 5.0.3 on 2024-03-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0015_alter_examstatus_response_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='examstatus',
            name='category_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examstatus',
            name='question_catefory',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelquestion',
            name='question_type',
            field=models.CharField(choices=[('hard', 'hard'), ('medium', 'medium'), ('easy', 'easy')], default='', max_length=255),
            preserve_default=False,
        ),
    ]
