# Generated by Django 5.0.3 on 2024-03-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0016_examstatus_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='question_type',
            field=models.CharField(choices=[('hard', 'hard'), ('medium', 'medium'), ('easy', 'easy')], default='esay', max_length=255),
            preserve_default=False,
        ),
    ]
