# Generated by Django 5.0.3 on 2024-03-30 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EECommittee', '0003_course_slug'),
        ('instructor', '0018_rename_question_catefory_examstatus_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='examstatus',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='examstatus', to='EECommittee.department'),
            preserve_default=False,
        ),
    ]
