# Generated by Django 5.0.3 on 2024-03-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EECommittee', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
